#!/bin/bash

. header.sh
. functions.ksh

cd "$WRK"
WDIR=$(hostname)$$
Workdir "$WDIR"

trap "Trapbody $WDIR ; exit 1" 0

FC_START=$( grep "000|" "$WRK"/bdstrategy | awk '{print substr($2,1)}' )
[[ -s $FC_START ]] || { echo "Could not find $FC_START" ; exit 1 ; }

# If surface == old_surface we blend surface fields from the surface analysis with 
# the boundary file and re-link this file to fc_start 
if [ "$SURFACE" == "old_surface" ] && [ "$ANAATMO" == "blending" ]; then

  if [ "$ANASURF" != "none" ]; then
    echo "Use $FC_START as initial file to be blended with the CANARI analysis"
    cp "$ARCHIVE"/ICMSHANAL+0000 FILE1
    cp "$FC_START" FILE2
    cp "$FC_START" FILE3
  else
    echo "Use $FC_START as initial file to be blended with the first guess"
    cp "$WRK"/blend_first_guess FILE1
    cp "$FC_START" FILE2
    cp "$FC_START" FILE3
  fi 

    # Fields to blend for aladin physics
    cl_cvarb[1]='PROFTEMPERATURE '
    cl_cvarb[2]='PROFRESERV.EAU  '
    cl_cvarb[3]='SURFTEMPERATURE '
    cl_cvarb[4]='SURFRESERV.EAU  '
    cl_cvarb[5]='SURFRESERV.INTER'
    cl_cvarb[6]='SURFRESERV.NEIGE'
    cl_cvarb[7]='SURFRESERV.GLACE'
    cl_cvarb[8]='PROFRESERV.GLACE'
    cl_cvarb[9]='SURFDENSIT.NEIGE'
    cl_cvarb[10]='SURFRES.EVAPOTRA'
    cl_cvarb[11]='SURFALBEDO NEIGE'
    cl_cvarb[12]='SURFALBEDO.SOLNU'
    cl_cvarb[13]='SURFALBEDO.VEG'
    cl_cvarb[14]='SURFAEROS.SEA'
    cl_cvarb[15]='SURFAEROS.LAND'
    cl_cvarb[16]='SURFAEROS.SOOT'
    cl_cvarb[17]='SURFAEROS.DESERT'
    if [ "$ANASURF" != "none" ]; then
      cl_cvarb[18]='SURFALBEDO HISTO'
      cl_cvarb[19]='CLSTEMPERATURE'
      cl_cvarb[20]='CLSHUMI.RELATIVE'
      cl_cvarb[21]='CLSVENT.ZONAL'
      cl_cvarb[22]='CLSVENT.MERIDIEN'
    fi

  # Create namelist
  i_nvarb=${#cl_cvarb[@]}
  cat > fort.4 <<EOF
  &NAMSCEN
  /
  &NAMDYNCORE
  /
  &namblendsur
   CL_FNAME1='FILE1',
   CL_FNAME2='FILE2', 
   CL_FNAME3='FILE3', 
   ZSIGNL=0.,
   ZSIGNS=0.,
   I_NVARB=$i_nvarb,
EOF

  # Add namelist fields to blend
  var=1
  while [ "$var" -le "$i_nvarb" ]; do
    echo "   CL_CVARB($var)='${cl_cvarb[$var]}'," >> fort.4
    var=$(( var + 1 ))
  done

  # Close namelist
  cat >> fort.4 << EOF
/ 
EOF

  export DR_HOOK_NOT_MPI=1

  $MPPGL "$BINDIR"/BLENDSUR

  if [ "$ANASURF" != "none" ]; then

    mv FILE3 "$ARCHIVE"/ANAL_CAN_BLENDED 

    # Relink fc start
    ln -sf "$ARCHIVE"/ANAL_CAN_BLENDED "$WRK"/fc_start
  else

    mv FILE3 "$ARCHIVE"/BLENDED_SURF

    # Relink fc start
    ln -sf "$ARCHIVE"/BLENDED_SURF "$WRK"/fc_start
  fi

elif [ "$SURFACE" == surfex ] && [ "$ANAATMO" == blending ]; then
  # If surfex we need to re-link fc_start to the boundary file as this was re-linked for CANARI previously
  # fc_start is used for main file in the blending

  echo "For surfex we make sure that fc_start is symlinked to the boundary file"
  ln -sf "$FC_START" "$WRK"/fc_start

# Sanity check
else
  echo "This script should only be used together with ANAATMO=blending"
  exit 1
fi

# Normal exit
cd ..
rm -fr "$WDIR"
trap - 0
exit
