#!/bin/ksh

#
# Build IFS binaries with gmkpack
#

. header.sh

#
# Build your own gmkpack
# For Harmonie we use $GMKROOT/support for $GMK_SUPPORT
#

export GMK_SUPPORT=$GMKROOT/support
export SHELL=/bin/ksh


#
# Make a crude check of ROOTPACK health
#

ROOTDIR=$ROOTPACK/${REVISION}_$BRANCH.$VERSION.$LIBFRT.$OPTION
# Existance
[[ -s $ROOTDIR ]] || { echo "Could not find $ROOTDIR" ; exit 1 ; }
# Do we have any libraries
[[ $( ls -1 $ROOTDIR/lib | wc -l ) -eq 0 ]] && { echo "No libraries found in $ROOTDIR/lib" ; exit 1 ; }

#
# Build gmkpack
#

cd $GMKROOT
./build_gmkpack || exit

#
# Copy our own architecture file to the place where gmkpack expects it.
#

cp $GMKROOT/arch/$GMKFILE.$OPTION $GMKROOT/support/arch/.

#
# Create your own pack with gmkpack only if the ics-file 
# does not exist
#

export GMKFILE=$GMKFILE

for PROG in $OTHER_PROGRAMS ; do

if [ ! -s $HOMEPACK/gmkpack_build/ics_$PROG ] ; then
   gmkpack -r $REVISION -b $BRANCH -o $OPTION -v $VERSION -p $PROG -u gmkpack_build || exit
fi

done

#
# Sync possible changed sources
#

Sync_src || exit 

cd $HOMEPACK/gmkpack_build/

#
# Compile and link the other binares, sources may have changed
#

for PROG in $OTHER_PROGRAMS ; do

   ./ics_$PROG || exit
   
done

# Copy gmkpack compile binaries to HARMONIE BINDIR.
[ -d $BINDIR ] || mkdir $BINDIR
if [ "$OTHER_PROGRAMS" != "" ]; then
  mv $HOMEPACK/gmkpack_build/bin/* $BINDIR/.
fi 

#
# Rename executables where the action depends on the name
# Some system resolve symbolic links, that's why we make a copy
#
[[ -s $HOMEBIN/odbtools.x ]] && cp $HOMEBIN/odbtools.x $HOMEBIN/shuffle
[[ -s $HOMEBIN/CONVERT_ECOCLIMAP ]] && cp $HOMEBIN/CONVERT_ECOCLIMAP_PARAM $HOMEBIN/CONVER_ECOCLIMAP_PARAM

[[ -s $BINDIR/PINUTS ]] && cp $BINDIR/PINUTS $BINDIR/frodo
[[ -s $BINDIR/odbtools.x ]] && cp $BINDIR/odbtools.x $BINDIR/shuffle
[[ -s $BINDIR/ioassign ]] && cp $BINDIR/ioassign $BINDIR/IOASSIGN

# Normal exit
trap - 0
exit
