#!/bin/ksh

#
# Build gmkpack and create a mainpack
#


. header.sh


#
# Redefine PACK since we are creating a mainpack
# For Harmonie we use $GMKROOT/support for $GMK_SUPPORT
#

export HOMEPACK=$ROOTPACK
export HOMEBIN=$ROOTPACK/bin
export SHELL=/bin/ksh
export GMK_SUPPORT=$GMKROOT/support

cd $GMKROOT

./build_gmkpack || exit

#
# Copy our own architecture file to the place where gmkpack expects it.
#

cp $GMKROOT/arch/$GMKFILE.$OPTION $GMKROOT/support/arch/.

# Normal exit
trap - 0
exit
