#!/bin/bash

. header.sh
. functions.ksh

cd $WRK
WDIR=`hostname`$$
Workdir $WDIR

trap "Trapbody $WDIR ; exit 1" 0

## Interpolate low res analysis to full res with Fullpos

loop=${1?"Loop number not given as input"}
res=$( echo $ILRES | cut -d, -f$loop )


BDCLIM=${CLIMDIR}_${res}x

LLL=$( perl -e "printf('%4.4i', $FCINT - 1)" )
INFILE=$WRK/MXMINI999_${res}x+0000
OUTFILE=$WRK/MXMINI999_b+0000

E927 -h -$LLL -i $INFILE -o $OUTFILE -v BOUNDARIES || exit

# Archive analysis from the beginnig of the window
cp $OUTFILE $ARCHIVE/an_begwin

# Normal exit
cd ..
rm -fr $WDIR
trap - 0
exit
