#!/bin/bash

#
# Build utilities
#


. header.sh

# Sync possible changed sources

MYTASK=monitor

cd $HM_LIB/util/$MYTASK/ || exit

$MAKE ARCH=$HARMONIE_CONFIG || exit 1

[[ -s $BINDIR ]] || mkdir -p $BINDIR

# Copy binaries to main bin directory
[[ -s ./bin ]] && cp bin/* $BINDIR/.
[[ -s ./$HARMONIE_CONFIG/bin ]] && cp ./$HARMONIE_CONFIG/bin/* $BINDIR/.

trap - 0
exit
