#!/bin/bash

#
# Build gl_grib_api
#

. header.sh

if [ $MAKEUP == "yes" ] ; then

  # Define makeup settings

  FAPATH=${MAKEUP_BUILD_DIR-$HM_LIB/$HARMONIE_CONFIG/}
  FALIB_PATH=$FAPATH/src
  FAINC_PATH=$FAPATH/src

else

  # Define gmkpack settings
  # Handle local changes in IFS libs by add the changes to a
  # local copy of the main library.

  FAPATH=$HM_LIB/util/gl_grib_api/$HARMONIE_CONFIG/falib
  [[ -s $FAPATH ]] || $MKDIR $FAPATH
  cd $FAPATH || exit

  FAINC_PATH=$HOMEPACK/gmkpack_build
  FALIB_PATH=$FAPATH

  FAPROJ=""
  for F in biper arpifs etrans trans algor ifsaux surfex mse mpa ; do
    cp $HOMEPACK/gmkpack_build/lib/lib${F}.main.a lib${F}.local.a
    if [ -s $HOMEPACK/gmkpack_build/lib/lib${F}.local.a ] ; then

      for O in $( ar -t $HOMEPACK/gmkpack_build/lib/lib${F}.local.a ) ; do 
       ar -x $HOMEPACK/gmkpack_build/lib/lib${F}.local.a $O
       ar -rv ./lib${F}.local.a $O
       rm -f $O
      done
    fi
    FAPROJ="$FAPROJ -l${F}.local"
  done
fi


# Run make

cd $HM_LIB/util/gl_grib_api/ || exit

$MAKE ARCH=$HARMONIE_CONFIG FAINC_PATH=$FAINC_PATH FALIB_PATH=$FALIB_PATH || exit 1


# Copy binaries to main bin directory
[[ -s $BINDIR ]] || $MKDIR $BINDIR
[[ -s ./$HARMONIE_CONFIG/bin ]] && cp ./$HARMONIE_CONFIG/bin/* $BINDIR/.

trap - 0

exit
